### ISSUE TITLE
need to output `clusterProfile.resourceGroupId`  and ideally let the user set it in the first place.

### ISSUE THREAD

**Issue by paulczar** [rh-mobb/terraform-provider-azureopenshift#1]
looking for equivalent of `az aro show --name openshift-cluster-aro --resource-group spoke-aro --query 'clusterProfile.resourceGroupId'`

post-cluster deployment a user may want this RG name to be able to list LBs etc in the RG that have been created by the cluster.

**Comment by datianshi** [comment]
Resource Group ID is exposed at v0.0.5

```
   cluster_profile {
        domain            = "xxx"
        resource_group_id = "xxx"
    }
```
