### ISSUE TITLE
TF should provide an output for the cluster ID that is used for host names and LB names

### ISSUE THREAD

**Issue by paulczar** [rh-mobb/terraform-provider-azureopenshift#2]
Connecting Front Door to ARO requires knowing the LB name being used which is "${cluster-id}-internal" to get to its IPs.  Currently need to shell out to figure it out, would be nice to be able to just use the data.azurerm_lb directly and construct the name from known properties.

The API itself doesn't provide the needed information directly, but it can be gleaned by something like the following

```
$ az aro show -n mobb-infra-aro -g mobb-infra-aro | jq -r '.workerProfiles[0].name' | sed 's/^\(.*\)-worker.*$/\1/'
```

---------------
example TF workaround
```

data "external" "aro_ilb_name" {
  program = [
    "az", "network", "lb", "list", "-g", var.aro_resource_group_name, "--query", "[0].{name:name}", "-o", "json"
  ]
}

data "azurerm_lb" "aro_ilb" {
  name = data.external.aro_ilb_name.result.name
  resource_group_name = var.aro_resource_group_name
}

resource "azurerm_private_link_service" "pl" {
  name = var.afd_pls_name
  resource_group_name = var.spoke_rg_name
  location = var.location

  nat_ip_configuration {
    name = "primary"
    private_ip_address_version = "IPv4"
    subnet_id = var.aro_worker_subnet_id
    primary = true
  }
  load_balancer_frontend_ip_configuration_ids = ["${data.azurerm_lb.aro_ilb.frontend_ip_configuration[0].id}"]
}
```

**Comment by datianshi** [comment]
https://registry.terraform.io/providers/rh-mobb/azureopenshift/0.0.6. 

This provides a field of internal_cluster_id

    internal_cluster_id = "flgk2"
