### ISSUE TITLE
outputs: apiserver IP + ingress IP

### ISSUE THREAD

**Issue by davidkarlsen** [rh-mobb/terraform-provider-azureopenshift#26]
We create private clusters and custom domain, and hence need to register the DNS-entries - and it would be nice to read the IPs of API and ingress as outputs from the resource

**Comment by datianshi** [comment]
@davidkarlsen  This is available with 0.0.17. 

You do things like this 

output api_server_ip {
    value = azureopenshift_redhatopenshift_cluster.cluster.api_server_profile[0].ip
}

output console_ingress_ip {
    value = azureopenshift_redhatopenshift_cluster.cluster.ingress_profile[0].ip
}

**Comment by davidkarlsen** [comment]
Just found it recent commit. But no mention in terraform registry docs
