### ISSUE TITLE
Error at the end of ARO creation with version 0.06: Error: can not capture the internal cluster id 

### ISSUE THREAD

**Issue by gahuja** [rh-mobb/terraform-provider-azureopenshift#3]
Getting the following error at the end of an ARO cluster creation when using version 0.06 of the provider

Error: can not capture the internal cluster id with cluster name aro-cluster-name, profile worker name aro-001-some-more-text-worker-eastus21, matches: []

   with azureopenshift_redhatopenshift_cluster.cluster,
   on main.tf line 39, in resource "azureopenshift_redhatopenshift_cluster" "cluster":
   39: resource "azureopenshift_redhatopenshift_cluster" "cluster" {

I changed the terraform.tf to point to version 0.05 and then things work fine.

**Comment by datianshi** [comment]
@gahuja  Thanks for asking. Do you mind sharing the exact cluster name you are using?  FYI, 0.0.6 we are trying to extract an internal cluster ID from the worker profile name. The pattern is like ${cluster_name}-${cluster_id}-worker-${region}${index}

**Comment by gahuja** [comment]
Here is the cluster name  with some text obfuscated
aro-001-xxxx-cp4i-dev-use2

Here is the error I got
Error: can not capture the internal cluster id with cluster name aro-001-xxxx-cp4i-dev-use2, profile worker name aro-001-xxxx-cp4i-dev-vzqfl-worker-eastus21, matches

**Comment by datianshi** [comment]
@gahuja  Thanks for reporting this. It is fixed in 0.0.8.
