### ISSUE TITLE
Generate ARO clusters with the customer-managed key (Key Vault)

### ISSUE THREAD

**Issue by rcarrata** [rh-mobb/terraform-provider-azureopenshift#5]
As is described in the https://learn.microsoft.com/en-us/azure/openshift/howto-byok#create-an-azure-red-hat-openshift-cluster guide, deploy an ARO cluster encrypting the OS disks with a customer-managed key (Key Vault).

--disk-encryption-set $DES_ID

**Comment by datianshi** [comment]
@rcarrata  -> https://registry.terraform.io/providers/rh-mobb/azureopenshift/latest. added the configuration. If you add disk_encryption_set at both master and worker profile. It should work
